<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\DeliveryFeePayer;
use App\Enums\DeliveryFeePaymentMethod;
use App\Enums\DeliveryFeeStatus;
use App\Enums\ItemSize;
use App\Enums\OrderStatus;
use App\Enums\OrderType;
use App\Enums\ReceiverType;
use App\Models\Order;
use App\Models\User;
use Clickbar\Magellan\Data\Geometries\Point;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Order>
 */
final class OrderFactory extends Factory
{
    protected $model = Order::class;

    public function definition(): array
    {
        // Match the project convention used in PresenceService and CreationService:
        // makeGeodetic(lat, lng) — reads SRID 4326 from config('magellan.geodetic_default_srid').
        $tripoli = Point::makeGeodetic(32.8872, 13.1913);

        return [
            // identity — auto-generated by booted() hook, but define for clarity
            // 'public_id' and 'tracking_token' are set by Order::booted()

            // type & status
            'order_type' => OrderType::StandardDelivery->value,
            'status' => OrderStatus::Created->value,
            'status_changed_at' => now(),

            // sender — FK resolved by state override; default to a new user
            'sender_user_id' => User::factory(),
            'sender_phone' => '+2189'.fake()->unique()->numerify('########'),
            'sender_name' => fake()->name(),

            // pickup
            'pickup_address' => fake()->address(),
            'pickup_location' => $tripoli,
            'pickup_notes' => null,
            'pickup_code' => (string) fake()->numerify('####'),
            'pickup_code_attempts' => 0,

            // receiver — guest by default (no FK needed)
            'receiver_type' => ReceiverType::Guest->value,
            'receiver_user_id' => null,
            'receiver_guest_id' => null,
            'receiver_phone' => '+2189'.fake()->unique()->numerify('########'),
            'receiver_name' => fake()->name(),
            'receiver_address' => fake()->address(),
            'receiver_location' => $tripoli,
            'receiver_notes' => null,
            'delivery_code' => (string) fake()->numerify('####'),
            'delivery_code_attempts' => 0,

            // item
            'item_description' => fake()->sentence(),
            'item_size' => ItemSize::Small->value,

            // financial
            'delivery_fee_base' => '5.00',
            'delivery_fee_surcharge_percent' => 0,
            'delivery_fee' => '5.00',
            'delivery_fee_payer' => DeliveryFeePayer::Sender->value,
            'delivery_fee_payment_method' => DeliveryFeePaymentMethod::Cash->value,
            'delivery_fee_status' => DeliveryFeeStatus::Unpaid->value,
        ];
    }

    /**
     * Order with a registered receiver user (sets receiver_type accordingly).
     */
    public function withReceiverUser(User $receiver): static
    {
        return $this->state([
            'receiver_type' => ReceiverType::RegisteredUser->value,
            'receiver_user_id' => $receiver->id,
        ]);
    }
}
